7x ci: unset PYTHONHOME, PYTHONPATH, and LD_LIBRARY_PATH
PYTHONHOME, PYTHONPATH, and LD_LIBRARY_PATH needs to be unset before
running 7x pg_isolation2_regress. Since 6x cluster will be sourced
by 6x greenplum_path.sh, if this is not done, 7x isolation2 will use
6x environment and encounter the following errors.

Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

  File "./sql_isolation_testcase.py", line 21, in <module>
    import subprocess
  File "/usr/lib64/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: dynamic module does not define module export function (PyInit__posixsubprocess)

Traceback (most recent call last):
  File "./sql_isolation_testcase.py", line 21, in <module>
    import subprocess
  File "/usr/lib64/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory