pg_upgrade: set PYTHONPATH for local testing
Set PYTHONPATH directly since it is needed when running the pg_upgrade
tests locally. Normally one would source greenplum_path.sh, but that
causes the following issues:
https://web.archive.org/web/20220506055918/https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/JN-YwjCCReY/m/0L9wBOvlAQAJ

Without setting this locally one will see the following error:
```
  File "./sql_isolation_testcase.py", line 18, in <module>
    import pygresql.pg
ImportError: No module named pygresql.pg
```

Or if one sourced greenplum_path.sh:
```
 /usr/local/gpdb6/bin/psql: symbol lookup error: /usr/local/gpdb6/bin/psql: undefined symbol: PQencryptPasswordConn
```