drop all materialized views when upgrading from 6X
Running analyze post-upgrade fails for materialized views with teh
following error:

vacuumdb: vacuuming of database "regression" failed:
ERROR:  read beyond eof in table "m_aocs" file "base/60402/26105", read
position 0 (small offset 0), actual read length 0 (large read length 48)
(cdbbufferedread.c:211)  (seg1 10.0.154.25:20001 pid=18253)
(cdbbufferedread.c:211)

For now just drop all materialized views.