CI: use rhel 8 instead of centos
Red Hat has terminated CentOS development and centos 8 was EOL’d. Thus,
the following error was according when performing a yum install:
```
yum install --quiet -y openssh-clients
Error: Failed to download metadata for repo 'appstream': Cannot prepare
internal mirrorlist: No URLs in mirrorlist
```

Use the offical rhel 8 image.