Update pg_upgrade acceptance tests upgradeable source schedule
The first parallel test group in the test schedule may open up too
many database connections (compared to the max_connections GUC setting
which is set to 25 in our CI) and can cause one of the tests to hit
this error:
```
ERROR:  failed to acquire resources on one or more segments
DETAIL:  FATAL:  sorry, too many clients already
```

Simply move some of the newer tests over to the next parallel group to
prevent the error.